# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Charlie Wilson
description: "I’m Charlie Wilson — a former portfolio manager and global investor with 20+ years of experience across emerging and developed markets. Today, I’m focused on applying data science and quantitative analysis to real-world challenges in development finance, economics, and technology. Let’s connect — I’m always open to collaboration or conversation."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Washington D.C."
resume_url: /docs/CharlieWilson_CV.pdf
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/charlie-wilson-dc" # Add your linkedln handle
github: "https://github.com/wilsonck75"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


